attributes:
- name: attr_1
  type: categorical
  values:
  - 0
  - 1
- name: attr_2
  type: categorical
  values:
  - 0
  - 1
- name: attr_3
  type: categorical
  values:
  - 0
  - 1
- name: attr_4
  type: categorical
  values:
  - 0
  - 1
- name: attr_5
  type: categorical
  values:
  - 0
  - 1
- name: attr_6
  type: categorical
  values:
  - 0
  - 1
- name: attr_7
  type: categorical
  values:
  - 0
  - 1
- name: attr_8
  type: categorical
  values:
  - 0
  - 1
- name: attr_9
  type: categorical
  values:
  - 0
  - 1
- name: attr_10
  type: categorical
  values:
  - 0
  - 1
- name: attr_11
  type: categorical
  values:
  - 0
  - 1
- name: attr_12
  type: categorical
  values:
  - 0
  - 1
- name: attr_13
  type: categorical
  values:
  - 0
  - 1
- name: attr_14
  type: categorical
  values:
  - 0
  - 1
- name: attr_15
  type: categorical
  values:
  - 0
  - 1
- name: attr_16
  type: categorical
  values:
  - 0
  - 1
